export interface CitiesCards {
    id: number,
    name: string,
    region: string,
    year: number,
    population: number,
    oldnames: string,
    photos: [
        {file: string, name: string},
        {file: string, name: string},
        {file: string, name: string},
        {file: string, name: string},
        {file: string, name: string},
        {file: string, name: string},
        {file: string, name: string},
        {file: string, name: string},
        {file: string, name: string},
        {file: string, name: string},
    ],
    short_description: string,
    history_description: string,
    climate_description: string,
    districts_description: string,
    economics_description: string,
    landmarks: [string, string, string, string, string, string, string, string, string, string],
}
